(function () {
    "use strict";
    var form=document.getElementById("diamond_feed"),submitButton=document.getElementById("diamond_submit"),uploadInput=document.getElementById("diamond_upload_image"),fetchedImage=document.getElementById("fetched_image"),emptyState=document.getElementById("diamond_image_empty"),cameraModal=$("#diamond_camera_modal"),cropModal=$("#diamond_crop_modal"),video=document.getElementById("diamond_video"),cameraSelect=document.getElementById("diamond_camera_select"),cropImage=document.getElementById("diamond_crop_image"),cameraStream=null,cameraCropper=null,selectedCameraId="";
    function uploadToken(){var field=document.getElementById("upload_token");if(!field.value){var random=window.crypto&&crypto.getRandomValues?Array.from(crypto.getRandomValues(new Uint32Array(2))).map(function(v){return v.toString(36)}).join(""):Math.random().toString(36).slice(2);field.value="d"+Date.now().toString(36)+random}return field.value}
    function showPreview(html){fetchedImage.innerHTML=html;var image=fetchedImage.querySelector("img");if(image){emptyState.style.display="none"}}
    function resetImage(){fetchedImage.innerHTML="";emptyState.style.display="block"}
    function stoneNameMaster(){var stoneName=$.trim($("#stone_name").val());if(!stoneName)return;$.ajax({url:"fetch_master_details.php",method:"POST",dataType:"json",data:{master_stone_name:stoneName}}).done(function(data){if(!data||data.status==="not_found")return;if(!$("#shape_cut").val()&&data.shape_cut)$("#shape_cut").val(data.shape_cut);if(!$("#colour").val()&&data.colour)$("#colour").val(data.colour);if(!$("#origin").val()&&data.origin)$("#origin").val(data.origin)})}
    function fetchImage(){var token=uploadToken();$.ajax({url:"image_fetch.php",method:"POST",data:{input:"",upload_token:token}}).done(function(html){showPreview(html)}).fail(function(){AppToast.error("Unable to fetch image.")})}
    function setLocalDate(){if(!$("#date").val()){var now=new Date(),local=new Date(now.getTime()-now.getTimezoneOffset()*60000);$("#date").val(local.toISOString().slice(0,10))}}
    function validate(){var required=["date","dia_wt","shape_cut","dimension","colour","comments"],valid=true;$(".diamond-field").removeClass("has-error");required.some(function(id){var field=document.getElementById(id);if(!field||!field.value.trim()){$(field).closest(".diamond-field").addClass("has-error");field.focus();AppToast.error("Please complete "+$(field).closest(".diamond-field").find("label").text().replace(" *","")+".");valid=false;return true}return false});return valid}
    form.addEventListener("submit",function(event){event.preventDefault();if(!validate())return;$("#weight").val($("#dia_wt").val());var data=new FormData(form);data.set("upload_token",uploadToken());submitButton.disabled=true;submitButton.innerHTML='<i class="fa fa-spinner fa-spin"></i> Saving...';$.ajax({url:"process-form.php",method:"POST",data:data,processData:false,contentType:false,dataType:"json"}).done(function(response){if(!response||response.status!=="success"){AppToast.error(response&&response.message?response.message:"Unable to save diamond report.");return}$("#diamond_saved_certificate").text(response.certi_no);$("#diamond_saved_report").text(response.report_no);$("#diamond_save_result").css("display","flex");AppToast.success("Diamond report saved. Certificate "+response.certi_no+" · Report "+response.report_no,6500);form.reset();document.getElementById("upload_token").value="";$("#stone_name").val("Diamond");setLocalDate();resetImage();$("#date").focus()}).fail(function(xhr){var message="Unable to save diamond report.";try{message=JSON.parse(xhr.responseText).message||message}catch(error){}AppToast.error(message)}).always(function(){submitButton.disabled=false;submitButton.innerHTML='<i class="fa fa-check"></i> Submit Form'})});
    uploadInput.addEventListener("change",function(){if(!this.files||!this.files[0])return;var data=new FormData();data.append("image_file",this.files[0]);data.append("certino","");data.append("upload_token",uploadToken());$.ajax({url:"upload.php",method:"POST",data:data,processData:false,contentType:false}).done(function(html){$("#diamond_folder_modal").modal("hide");showPreview(html);AppToast.success("Diamond image attached.")}).fail(function(xhr){AppToast.error(xhr.responseText||"Unable to upload image.")});this.value=""});
    document.getElementById("diamond_fetch_image").addEventListener("click",fetchImage);
    document.addEventListener("keydown",function(event){if(event.keyCode===119){event.preventDefault();fetchImage()}});
    document.getElementById("diamond_copy_button").addEventListener("click",function(){var certificate=$.trim($("#diamond_copy_certificate").val());if(!certificate){$("#diamond_copy_block").addClass("has-error");$("#diamond_copy_certificate").focus();AppToast.error("Please enter a certificate number.");return}$.ajax({url:"field-cpier.php",method:"POST",dataType:"json",data:{field_no:certificate,report_type:"D"}}).done(function(data){if(!data){AppToast.error("Diamond certificate not found.");return}$("#diamond_copy_block").removeClass("has-error");$("#date").val(data.date||"");$("#stone_name").val(data.stone_name||"Diamond");$("#dia_wt").val(data.dia_wt||data.stone_wt||"");$("#shape_cut").val(data.shape_cut||"");$("#dimension").val(data.dimension||"");$("#colour").val(data.color||"");$("#clarity").val(data.clarity||"");$("#issued_to").val(data.issued_to||"");$("#finish").val(data.finish||"");$("#cut").val(data.cut||"");$("#table_value").val(data.table||"");$("#crown").val(data.crown||"");$("#girdle").val(data.girdle||"");$("#pav_depth").val(data.pav_depth||"");$("#tab_depth").val(data.tab_depth||"");$("#flurance").val(data.flurance||"");$("#origin").val(data.origin||"");$("#comments").val(data.comment||data.rem1||"");AppToast.success("Diamond report fields copied from certificate "+certificate+".")}).fail(function(){AppToast.error("Unable to copy certificate fields.")})});
    $("#stone_name").on("change blur",stoneNameMaster);
    function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(function(track){track.stop()});cameraStream=null}video.srcObject=null}
    async function listCameras(){var devices=await navigator.mediaDevices.enumerateDevices(),cameras=devices.filter(function(device){return device.kind==="videoinput"});cameraSelect.innerHTML="";cameras.forEach(function(camera,index){var option=document.createElement("option");option.value=camera.deviceId;option.textContent=camera.label||"Camera "+(index+1);cameraSelect.appendChild(option)});cameraSelect.disabled=cameras.length<=1;if(selectedCameraId&&cameras.some(function(camera){return camera.deviceId===selectedCameraId})){cameraSelect.value=selectedCameraId}else{selectedCameraId=cameraSelect.value}}
    async function startCamera(deviceId){stopCamera();if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){AppToast.error("Camera access requires HTTPS or localhost.");cameraModal.modal("hide");return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:"environment"}},audio:false});video.srcObject=cameraStream;await video.play();await listCameras()}catch(error){AppToast.error("Unable to open the selected camera.");cameraModal.modal("hide")}}
    cameraModal.on("shown.bs.modal",function(){startCamera(selectedCameraId)});cameraModal.on("hidden.bs.modal",stopCamera);cameraSelect.addEventListener("change",function(){selectedCameraId=this.value;startCamera(selectedCameraId)});
    document.getElementById("diamond_capture").addEventListener("click",function(){if(!video.videoWidth){AppToast.warning("Camera is still starting.");return}var canvas=document.createElement("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d").drawImage(video,0,0);cropImage.src=canvas.toDataURL("image/jpeg",.92);stopCamera();cameraModal.modal("hide");cropModal.modal("show")});
    cropModal.on("shown.bs.modal",function(){if(cameraCropper)cameraCropper.destroy();cameraCropper=new Cropper(cropImage,{aspectRatio:1,viewMode:3,autoCropArea:1})});cropModal.on("hidden.bs.modal",function(){if(cameraCropper)cameraCropper.destroy();cameraCropper=null});
    document.getElementById("diamond_crop_save").addEventListener("click",function(){if(!cameraCropper)return;var croppedData=cameraCropper.getCroppedCanvas({width:800,height:800}).toDataURL("image/jpeg",.9);$.post("save_image.php",{croppedData:croppedData,certino:"",upload_token:uploadToken()}).done(function(html){cropModal.modal("hide");showPreview(html);AppToast.success("Diamond image captured.")}).fail(function(xhr){AppToast.error(xhr.responseText||"Unable to save camera image.")})});
    form.addEventListener("reset",function(){window.setTimeout(function(){$("#stone_name").val("Diamond");setLocalDate()},0)});setLocalDate();
})();
