<?php
require_once 'auth.php';
auth_require_login();
require_once 'db_connect.php';
require_once 'master_data_helper.php';
include "assets/navbar.php";
?>
<link href="../css/cropper.min.css" rel="stylesheet">
<style>
.diamond-page{padding-bottom:34px}.diamond-head{border-bottom:1px solid #ececf1;margin-bottom:22px;padding-bottom:16px}.diamond-head h1{border:0;color:#171717;font-size:24px;font-weight:600;margin:0 0 5px;padding:0}.diamond-head p{color:#737373;font-size:13px;margin:0}
.diamond-layout{align-items:start;display:grid;gap:18px;grid-template-columns:minmax(0,1fr) 320px}.diamond-main{display:flex;flex-direction:column;gap:15px}.diamond-card{background:#fff;border:1px solid #ececf1;border-radius:10px;overflow:hidden}.diamond-card-head{border-bottom:1px solid #ececf1;padding:14px 18px}.diamond-card-head h3{font-size:14px;font-weight:600;margin:0}.diamond-card-body{padding:17px 18px}.diamond-grid{display:grid;gap:14px 16px;grid-template-columns:repeat(2,minmax(0,1fr))}.diamond-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.diamond-field label{color:#404040;display:block;font-size:12px;font-weight:500;margin-bottom:6px}.diamond-field .form-control{border-radius:8px;box-shadow:none;min-height:40px}.diamond-field.has-error .form-control{border-color:#dc2626}.diamond-field.full{grid-column:1/-1}.diamond-actions{align-items:center;display:flex;flex-wrap:wrap;gap:9px}.diamond-actions .btn{border-radius:8px;min-height:40px}.diamond-action-spacer{flex:1}.diamond-save{background:#171717;border-color:#171717;color:#fff}.diamond-save:hover,.diamond-save:focus{background:#404040;color:#fff}
.diamond-side{position:sticky;top:82px}.image-stage{align-items:center;background:#f7f7f8;display:flex;height:260px;justify-content:center;overflow:hidden;position:relative}.image-stage img{height:260px;object-fit:contain;width:100%}.image-empty{color:#a3a3a3;text-align:center}.image-empty i{display:block;font-size:34px;margin-bottom:10px}.image-fetch{padding:0 14px 10px}.image-fetch .btn{border-radius:8px}.image-tools{display:grid;gap:8px;grid-template-columns:1fr 1fr;padding:0 14px 14px}.image-tools .btn{border-radius:8px}.camera-select-wrap{margin-bottom:12px}.copy-block{border-top:1px solid #ececf1;padding:14px}.copy-block label{color:#404040;font-size:12px;font-weight:500;margin-bottom:7px}.copy-row{display:grid;gap:7px;grid-template-columns:minmax(0,1fr) auto}.copy-row .form-control,.copy-row .btn{border-radius:8px;min-height:39px}.copy-block.has-error .form-control{border-color:#dc2626}.save-result{align-items:center;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;color:#166534;display:none;gap:8px;margin-bottom:15px;padding:10px 12px}.save-result strong{font-size:15px}
@media(max-width:1000px){.diamond-layout{grid-template-columns:1fr}.diamond-side{position:relative;top:auto}.diamond-grid.three{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.diamond-grid,.diamond-grid.three{grid-template-columns:1fr}.diamond-actions{align-items:stretch;flex-direction:column}.diamond-actions .btn{width:100%}}
</style>
<div id="page-wrapper"><div class="container-fluid diamond-page">
    <div class="diamond-head"><h1><i class="fa fa-diamond"></i> Diamond Report Feeding</h1><p>Enter grading details and save. Certificate and report numbers are assigned securely after submission.</p></div>
    <form id="diamond_feed" autocomplete="off">
        <input type="hidden" name="report_type" value="D"><input type="hidden" name="certi_no" id="certi_no" value=""><input type="hidden" name="upload_token" id="upload_token" value=""><input type="hidden" name="weight" id="weight" value="">
        <div class="diamond-layout">
            <div class="diamond-main">
                <div class="save-result" id="diamond_save_result"><i class="fa fa-check-circle"></i><span>Last saved: Certificate <strong id="diamond_saved_certificate"></strong> · Report <strong id="diamond_saved_report"></strong></span></div>
                <section class="diamond-card"><div class="diamond-card-head"><h3>Report Details</h3></div><div class="diamond-card-body"><div class="diamond-grid">
                    <div class="diamond-field"><label for="date">Date *</label><input class="form-control" type="date" name="date" id="date" required></div>
                    <div class="diamond-field"><label for="stone_name">Stone Name</label><input class="form-control" type="text" name="stone_name" id="stone_name" value="Diamond" list="diamond_stone_name_master" autocomplete="off"></div>
                    <div class="diamond-field"><label for="dia_wt">Diamond Weight *</label><div class="input-group"><input class="form-control" type="text" name="dia_wt" id="dia_wt" required><span class="input-group-addon">Cts</span></div></div>
                    <div class="diamond-field"><label for="shape_cut">Shape / Cut *</label><input class="form-control" type="text" name="shape_cut" id="shape_cut" list="diamond_shape_cut_master" autocomplete="off" required></div>
                    <div class="diamond-field"><label for="dimension">Measurement *</label><input class="form-control" type="text" name="dimension" id="dimension" required></div>
                    <div class="diamond-field"><label for="colour">Colour Grade *</label><input class="form-control" type="text" name="colour" id="colour" list="diamond_colour_master" autocomplete="off" required></div>
                    <div class="diamond-field"><label for="clarity">Clarity</label><input class="form-control" type="text" name="clarity" id="clarity"></div>
                    <div class="diamond-field"><label for="issued_to">Issued To</label><input class="form-control" type="text" name="issued_to" id="issued_to"></div>
                </div></div></section>
                <section class="diamond-card"><div class="diamond-card-head"><h3>Proportion &amp; Finish</h3></div><div class="diamond-card-body"><div class="diamond-grid three">
                    <div class="diamond-field"><label for="finish">Finish</label><input class="form-control" type="text" name="finish" id="finish"></div>
                    <div class="diamond-field"><label for="cut">Cut Grade</label><input class="form-control" type="text" name="cut" id="cut"></div>
                    <div class="diamond-field"><label for="table_value">Table</label><input class="form-control" type="text" name="table_value" id="table_value"></div>
                    <div class="diamond-field"><label for="crown">Crown Height</label><input class="form-control" type="text" name="crown" id="crown"></div>
                    <div class="diamond-field"><label for="girdle">Girdle</label><input class="form-control" type="text" name="girdle" id="girdle"></div>
                    <div class="diamond-field"><label for="pav_depth">Pavilion Depth</label><input class="form-control" type="text" name="pav_depth" id="pav_depth"></div>
                    <div class="diamond-field"><label for="tab_depth">Table Depth</label><input class="form-control" type="text" name="tab_depth" id="tab_depth"></div>
                    <div class="diamond-field"><label for="flurance">Fluorescence</label><input class="form-control" type="text" name="flurance" id="flurance"></div>
                    <div class="diamond-field"><label for="origin">Origin</label><input class="form-control" type="text" name="origin" id="origin"></div>
                    <div class="diamond-field full"><label for="comments">Comments *</label><textarea class="form-control" rows="3" name="comments" id="comments" required></textarea></div>
                </div></div></section>
                <div class="diamond-actions"><button type="submit" class="btn diamond-save" id="diamond_submit"><i class="fa fa-check"></i> Submit Form</button><button type="reset" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button><span class="diamond-action-spacer"></span><button class="btn btn-default" type="button" data-toggle="modal" data-target="#diamond_folder_modal"><i class="fa fa-folder-open-o"></i> Upload Image</button><button class="btn btn-default" type="button" data-toggle="modal" data-target="#diamond_camera_modal"><i class="fa fa-camera"></i> Camera</button></div>
            </div>
            <aside class="diamond-card diamond-side">
                <div class="diamond-card-head"><h3>Diamond Image</h3></div>
                <div class="image-stage"><div class="image-empty" id="diamond_image_empty"><i class="fa fa-picture-o"></i>No image selected</div><div id="fetched_image"></div></div>
                <div class="image-fetch"><button class="btn btn-danger btn-block" type="button" id="diamond_fetch_image"><i class="fa fa-download"></i> Fetch Image</button></div>
                <div class="image-tools"><button class="btn btn-default" type="button" data-toggle="modal" data-target="#diamond_folder_modal"><i class="fa fa-folder-open-o"></i> Upload</button><button class="btn btn-default" type="button" data-toggle="modal" data-target="#diamond_camera_modal"><i class="fa fa-camera"></i> Camera</button></div>
                <div class="copy-block" id="diamond_copy_block"><label for="diamond_copy_certificate">Copy from existing certificate</label><div class="copy-row"><input type="number" min="1" id="diamond_copy_certificate" class="form-control" placeholder="Certificate number"><button type="button" class="btn btn-primary" id="diamond_copy_button">Copy</button></div></div>
            </aside>
        </div>
    </form>
</div></div>
<datalist id="diamond_stone_name_master"><?php foreach (master_fetch_rows($conn, 'sm_master_stone_name', ['stone_name'], auth_current_user_id(), ['stone_name'], 'stone_name') as $row) { echo '<option value="' . htmlspecialchars($row['stone_name']) . '">'; } ?></datalist>
<datalist id="diamond_shape_cut_master"><?php foreach (master_fetch_rows($conn, 'sm_master_shape_cut', ['shape_cut'], auth_current_user_id(), ['shape_cut'], 'shape_cut') as $row) { echo '<option value="' . htmlspecialchars($row['shape_cut']) . '">'; } ?></datalist>
<datalist id="diamond_colour_master"><?php foreach (master_fetch_rows($conn, 'sm_master_colour', ['colour'], auth_current_user_id(), ['colour'], 'colour') as $row) { echo '<option value="' . htmlspecialchars($row['colour']) . '">'; } ?></datalist>
<div id="diamond_folder_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Select Image</h4></div><div class="modal-body"><div class="panel panel-default"><input type="file" id="diamond_upload_image" accept="image/jpeg,image/png" class="form-control"></div><span class="help-block">Please select a JPG or PNG image file. Cropping is not required for uploaded images.</span></div><div class="modal-footer"><button type="button" class="btn btn-primary" data-dismiss="modal">Close</button></div></div></div></div>
<div id="diamond_camera_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Get Frame and Snap Image</h4></div><div class="modal-body"><div class="camera-select-wrap"><label for="diamond_camera_select">Select Camera</label><select id="diamond_camera_select" class="form-control"><option value="">Detecting cameras...</option></select><small class="help-block">If multiple cameras are connected, choose the camera before taking the picture.</small></div><div class="panel panel-default"><video id="diamond_video" autoplay playsinline style="width:100%;background:#111"></video></div></div><div class="modal-footer"><button type="button" class="btn btn-primary" id="diamond_capture">Crop Image</button><button type="button" class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
<div id="diamond_crop_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Crop and Save Image</h4></div><div class="modal-body"><div class="img-container"><img id="diamond_crop_image" alt="Captured diamond" style="display:block;max-width:100%;width:100%"></div></div><div class="modal-footer"><button type="button" class="btn btn-primary" id="diamond_crop_save">Crop Image</button><button type="button" class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
<script src="../js/cropper.min.js"></script><script src="../js/diamond_form.js"></script>
<?php include "assets/footer.php"; ?>
