<?php
require_once 'auth.php';
auth_require_login();
require_once 'db_connect.php';
require_once 'master_data_helper.php';
include "assets/navbar.php";
?>
<link href="../css/cropper.min.css" rel="stylesheet">
<style>
.jewel-page{padding-bottom:34px}.jewel-head{border-bottom:1px solid #ececf1;margin-bottom:22px;padding-bottom:16px}.jewel-head h1{border:0;color:#171717;font-size:24px;font-weight:600;margin:0 0 5px;padding:0}.jewel-head p{color:#737373;font-size:13px;margin:0}.jewel-layout{align-items:start;display:grid;gap:18px;grid-template-columns:minmax(0,1fr) 320px}.jewel-main{display:flex;flex-direction:column;gap:15px}.jewel-card{background:#fff;border:1px solid #ececf1;border-radius:10px;overflow:hidden}.jewel-card-head{border-bottom:1px solid #ececf1;padding:14px 18px}.jewel-card-head h3{font-size:14px;font-weight:600;margin:0}.jewel-card-body{padding:17px 18px}.jewel-grid{display:grid;gap:14px 16px;grid-template-columns:repeat(2,minmax(0,1fr))}.jewel-field label{color:#404040;display:block;font-size:12px;font-weight:500;margin-bottom:6px}.jewel-field .form-control{border-radius:8px;box-shadow:none;min-height:40px}.jewel-field.has-error .form-control{border-color:#dc2626}.jewel-field.full{grid-column:1/-1}.jewel-actions{align-items:center;display:flex;flex-wrap:wrap;gap:9px}.jewel-actions .btn{border-radius:8px;min-height:40px}.jewel-action-spacer{flex:1}.jewel-save{background:#171717;border-color:#171717;color:#fff}.jewel-side{position:sticky;top:82px}.image-stage{align-items:center;background:#f7f7f8;display:flex;height:260px;justify-content:center;overflow:hidden}.image-stage img{height:260px;object-fit:contain;width:100%}.image-empty{color:#a3a3a3;text-align:center}.image-empty i{display:block;font-size:34px;margin-bottom:10px}.image-fetch{padding:0 14px 10px}.image-tools{display:grid;gap:8px;grid-template-columns:1fr 1fr;padding:0 14px 14px}.image-fetch .btn,.image-tools .btn,.copy-row .btn{border-radius:8px}.copy-block{border-top:1px solid #ececf1;padding:14px}.copy-row{display:grid;gap:7px;grid-template-columns:minmax(0,1fr) auto}.copy-row .form-control{border-radius:8px;min-height:39px}.copy-block.has-error .form-control{border-color:#dc2626}.save-result{align-items:center;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;color:#166534;display:none;gap:8px;margin-bottom:15px;padding:10px 12px}@media(max-width:1000px){.jewel-layout{grid-template-columns:1fr}.jewel-side{position:relative;top:auto}}@media(max-width:600px){.jewel-grid{grid-template-columns:1fr}.jewel-actions{flex-direction:column}.jewel-actions .btn{width:100%}}
</style>
<div id="page-wrapper"><div class="container-fluid jewel-page">
<div class="jewel-head"><h1><i class="fa fa-diamond"></i> Jewellery Report Feeding</h1><p>Enter jewellery analysis details and save. Certificate and report numbers are assigned automatically.</p></div>
<form id="jewellery_feed" autocomplete="off"><input type="hidden" name="report_type" value="J"><input type="hidden" name="upload_token" id="upload_token">
<div class="jewel-layout"><div class="jewel-main">
<div class="save-result" id="jewel_save_result"><i class="fa fa-check-circle"></i><span>Last saved: Certificate <strong id="jewel_saved_certificate"></strong> · Report <strong id="jewel_saved_report"></strong></span></div>
<section class="jewel-card"><div class="jewel-card-head"><h3>Report Details</h3></div><div class="jewel-card-body"><div class="jewel-grid">
<div class="jewel-field"><label for="date">Date *</label><input class="form-control" type="date" name="date" id="date" required></div>
<div class="jewel-field"><label for="stone_name">Stone Name</label><input class="form-control" name="stone_name" id="stone_name" list="jewel_stone_name_master" autocomplete="off"></div>
<div class="jewel-field full"><label for="description">Description *</label><textarea class="form-control" rows="3" name="description" id="description" required></textarea></div>
<div class="jewel-field"><label for="weight">Gross Weight *</label><input class="form-control" name="weight" id="weight" required></div>
<div class="jewel-field"><label for="dia_wt">Diamond Weight</label><input class="form-control" name="dia_wt" id="dia_wt"></div>
<div class="jewel-field"><label for="stone_pcs">Diamond Pcs</label><input class="form-control" name="stone_pcs" id="stone_pcs"></div>
<div class="jewel-field"><label for="shape_cut">Shape *</label><input class="form-control" name="shape_cut" id="shape_cut" list="jewel_shape_cut_master" autocomplete="off" required></div>
<div class="jewel-field"><label for="colour">Color *</label><input class="form-control" name="colour" id="colour" list="jewel_colour_master" autocomplete="off" required></div>
<div class="jewel-field"><label for="clarity">Clarity</label><input class="form-control" name="clarity" id="clarity"></div>
<div class="jewel-field"><label for="cut">Cut</label><input class="form-control" name="cut" id="cut"></div>
<div class="jewel-field full"><label for="comments">Comments</label><textarea class="form-control" rows="3" name="comments" id="comments"></textarea></div>
<div class="jewel-field"><label for="issued_to">Issued To</label><input class="form-control" name="issued_to" id="issued_to"></div>
</div></div></section>
<div class="jewel-actions"><button type="submit" class="btn jewel-save" id="jewel_submit"><i class="fa fa-check"></i> Submit Form</button><button type="reset" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button><span class="jewel-action-spacer"></span><button class="btn btn-default" type="button" data-toggle="modal" data-target="#jewel_folder_modal"><i class="fa fa-folder-open-o"></i> Upload Image</button><button class="btn btn-default" type="button" data-toggle="modal" data-target="#jewel_camera_modal"><i class="fa fa-camera"></i> Camera</button></div>
</div><aside class="jewel-card jewel-side"><div class="jewel-card-head"><h3>Jewellery Image</h3></div><div class="image-stage"><div class="image-empty" id="jewel_image_empty"><i class="fa fa-picture-o"></i>No image selected</div><div id="fetched_image"></div></div><div class="image-fetch"><button class="btn btn-danger btn-block" type="button" id="jewel_fetch_image"><i class="fa fa-download"></i> Fetch Image</button></div><div class="image-tools"><button class="btn btn-default" type="button" data-toggle="modal" data-target="#jewel_folder_modal"><i class="fa fa-folder-open-o"></i> Upload</button><button class="btn btn-default" type="button" data-toggle="modal" data-target="#jewel_camera_modal"><i class="fa fa-camera"></i> Camera</button></div><div class="copy-block" id="jewel_copy_block"><label for="jewel_copy_certificate">Copy from existing certificate</label><div class="copy-row"><input type="number" min="1" id="jewel_copy_certificate" class="form-control" placeholder="Certificate number"><button type="button" class="btn btn-primary" id="jewel_copy_button">Copy</button></div></div></aside></div>
</form></div></div>
<datalist id="jewel_stone_name_master"><?php foreach (master_fetch_rows($conn, 'sm_master_stone_name', ['stone_name'], auth_current_user_id(), ['stone_name'], 'stone_name') as $row) { echo '<option value="' . htmlspecialchars($row['stone_name']) . '">'; } ?></datalist>
<datalist id="jewel_shape_cut_master"><?php foreach (master_fetch_rows($conn, 'sm_master_shape_cut', ['shape_cut'], auth_current_user_id(), ['shape_cut'], 'shape_cut') as $row) { echo '<option value="' . htmlspecialchars($row['shape_cut']) . '">'; } ?></datalist>
<datalist id="jewel_colour_master"><?php foreach (master_fetch_rows($conn, 'sm_master_colour', ['colour'], auth_current_user_id(), ['colour'], 'colour') as $row) { echo '<option value="' . htmlspecialchars($row['colour']) . '">'; } ?></datalist>
<div id="jewel_folder_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4>Select Image</h4></div><div class="modal-body"><input type="file" id="jewel_upload_image" accept="image/jpeg,image/png" class="form-control"><span class="help-block">Select a JPG or PNG image. Uploaded images do not require cropping.</span></div></div></div></div>
<div id="jewel_camera_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4>Get Frame and Snap Image</h4></div><div class="modal-body"><label>Select Camera</label><select id="jewel_camera_select" class="form-control"><option>Detecting cameras...</option></select><br><video id="jewel_video" autoplay playsinline style="width:100%;background:#111"></video></div><div class="modal-footer"><button class="btn btn-primary" type="button" id="jewel_capture">Crop Image</button></div></div></div></div>
<div id="jewel_crop_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4>Crop and Save Image</h4></div><div class="modal-body"><img id="jewel_crop_image" alt="Captured Jewellery" style="display:block;max-width:100%;width:100%"></div><div class="modal-footer"><button class="btn btn-primary" type="button" id="jewel_crop_save">Crop Image</button></div></div></div></div>
<script src="../js/cropper.min.js"></script><script src="../js/jewellery_form.js"></script>
<?php include "assets/footer.php"; ?>
