<?php
require_once 'auth.php';
auth_require_login();
require_once 'db_connect.php';
require_once 'master_data_helper.php';
include "assets/navbar.php";
?>
<link href="../css/cropper.min.css" rel="stylesheet">
<style>
.rudra-page{padding-bottom:34px}.rudra-head{border-bottom:1px solid #ececf1;margin-bottom:22px;padding-bottom:16px}.rudra-head h1{border:0;color:#171717;font-size:24px;font-weight:600;margin:0 0 5px;padding:0}.rudra-head p{color:#737373;font-size:13px;margin:0}.rudra-layout{align-items:start;display:grid;gap:18px;grid-template-columns:minmax(0,1fr) 320px}.rudra-main{display:flex;flex-direction:column;gap:15px}.rudra-card{background:#fff;border:1px solid #ececf1;border-radius:10px;overflow:hidden}.rudra-card-head{border-bottom:1px solid #ececf1;padding:14px 18px}.rudra-card-head h3{font-size:14px;font-weight:600;margin:0}.rudra-card-body{padding:17px 18px}.rudra-grid{display:grid;gap:14px 16px;grid-template-columns:repeat(2,minmax(0,1fr))}.rudra-field label{color:#404040;display:block;font-size:12px;font-weight:500;margin-bottom:6px}.rudra-field .form-control{border-radius:8px;box-shadow:none;min-height:40px}.rudra-field.has-error .form-control{border-color:#dc2626}.rudra-field.full{grid-column:1/-1}.rudra-actions{align-items:center;display:flex;flex-wrap:wrap;gap:9px}.rudra-actions .btn{border-radius:8px;min-height:40px}.rudra-action-spacer{flex:1}.rudra-save{background:#171717;border-color:#171717;color:#fff}.rudra-side{position:sticky;top:82px}.image-stage{align-items:center;background:#f7f7f8;display:flex;height:260px;justify-content:center;overflow:hidden}.image-stage img{height:260px;object-fit:contain;width:100%}.image-empty{color:#a3a3a3;text-align:center}.image-empty i{display:block;font-size:34px;margin-bottom:10px}.image-fetch{padding:0 14px 10px}.image-tools{display:grid;gap:8px;grid-template-columns:1fr 1fr;padding:0 14px 14px}.image-fetch .btn,.image-tools .btn{border-radius:8px}.copy-block{border-top:1px solid #ececf1;padding:14px}.copy-row{display:grid;gap:7px;grid-template-columns:minmax(0,1fr) auto}.copy-row .form-control,.copy-row .btn{border-radius:8px;min-height:39px}.copy-block.has-error .form-control{border-color:#dc2626}.save-result{align-items:center;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;color:#166534;display:none;gap:8px;margin-bottom:15px;padding:10px 12px}@media(max-width:1000px){.rudra-layout{grid-template-columns:1fr}.rudra-side{position:relative;top:auto}}@media(max-width:600px){.rudra-grid{grid-template-columns:1fr}.rudra-actions{flex-direction:column}.rudra-actions .btn{width:100%}}
</style>
<div id="page-wrapper"><div class="container-fluid rudra-page">
<div class="rudra-head"><h1><i class="fa fa-circle-o"></i> Rudraksha Report Feeding</h1><p>Enter identification details. Certificate and report numbers are securely assigned after saving.</p></div>
<form id="rudraksha_feed" autocomplete="off"><input type="hidden" name="report_type" value="R"><input type="hidden" name="upload_token" id="upload_token"><input type="hidden" name="stone_name" value="Rudraksha">
<div class="rudra-layout"><div class="rudra-main">
<div class="save-result" id="rudra_save_result"><i class="fa fa-check-circle"></i><span>Last saved: Certificate <strong id="rudra_saved_certificate"></strong> · Report <strong id="rudra_saved_report"></strong></span></div>
<section class="rudra-card"><div class="rudra-card-head"><h3>Report Details</h3></div><div class="rudra-card-body"><div class="rudra-grid">
<div class="rudra-field"><label for="date">Date *</label><input class="form-control" type="date" name="date" id="date" required></div>
<div class="rudra-field"><label for="weight">Weight *</label><input class="form-control" name="weight" id="weight" required></div>
<div class="rudra-field full"><label for="description">Description *</label><textarea class="form-control" rows="3" name="description" id="description" required></textarea></div>
<div class="rudra-field"><label for="shape_cut">Shape *</label><input class="form-control" name="shape_cut" id="shape_cut" list="rudra_shape_cut_master" autocomplete="off" required></div>
<div class="rudra-field"><label for="dimension">Dimension *</label><input class="form-control" name="dimension" id="dimension" required></div>
<div class="rudra-field"><label for="colour">Color *</label><input class="form-control" name="colour" id="colour" list="rudra_colour_master" autocomplete="off" required></div>
<div class="rudra-field"><label for="faces">Face *</label><input class="form-control" name="faces" id="faces" required></div>
<div class="rudra-field full"><label for="comments">Specific Comments</label><textarea class="form-control" rows="3" name="comments" id="comments"></textarea></div>
<div class="rudra-field full"><label for="test_carried_out">Test Carried Out</label><textarea class="form-control" rows="3" name="test_carried_out" id="test_carried_out"></textarea></div>
<div class="rudra-field full"><label for="remarks">Remarks</label><textarea class="form-control" rows="3" name="remarks" id="remarks"></textarea></div>
<div class="rudra-field"><label for="issued_to">Issued To</label><input class="form-control" name="issued_to" id="issued_to"></div>
</div></div></section>
<div class="rudra-actions"><button type="submit" class="btn rudra-save" id="rudra_submit"><i class="fa fa-check"></i> Submit Form</button><button type="reset" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button><span class="rudra-action-spacer"></span><button class="btn btn-default" type="button" data-toggle="modal" data-target="#rudra_folder_modal"><i class="fa fa-folder-open-o"></i> Upload Image</button><button class="btn btn-default" type="button" data-toggle="modal" data-target="#rudra_camera_modal"><i class="fa fa-camera"></i> Camera</button></div>
</div><aside class="rudra-card rudra-side"><div class="rudra-card-head"><h3>Rudraksha Image</h3></div><div class="image-stage"><div class="image-empty" id="rudra_image_empty"><i class="fa fa-picture-o"></i>No image selected</div><div id="fetched_image"></div></div><div class="image-fetch"><button class="btn btn-danger btn-block" type="button" id="rudra_fetch_image"><i class="fa fa-download"></i> Fetch Image</button></div><div class="image-tools"><button class="btn btn-default" type="button" data-toggle="modal" data-target="#rudra_folder_modal"><i class="fa fa-folder-open-o"></i> Upload</button><button class="btn btn-default" type="button" data-toggle="modal" data-target="#rudra_camera_modal"><i class="fa fa-camera"></i> Camera</button></div><div class="copy-block" id="rudra_copy_block"><label for="rudra_copy_certificate">Copy from existing certificate</label><div class="copy-row"><input type="number" min="1" id="rudra_copy_certificate" class="form-control" placeholder="Certificate number"><button type="button" class="btn btn-primary" id="rudra_copy_button">Copy</button></div></div></aside></div>
</form></div></div>
<datalist id="rudra_shape_cut_master"><?php foreach (master_fetch_rows($conn, 'sm_master_shape_cut', ['shape_cut'], auth_current_user_id(), ['shape_cut'], 'shape_cut') as $row) { echo '<option value="' . htmlspecialchars($row['shape_cut']) . '">'; } ?></datalist>
<datalist id="rudra_colour_master"><?php foreach (master_fetch_rows($conn, 'sm_master_colour', ['colour'], auth_current_user_id(), ['colour'], 'colour') as $row) { echo '<option value="' . htmlspecialchars($row['colour']) . '">'; } ?></datalist>
<div id="rudra_folder_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4>Select Image</h4></div><div class="modal-body"><input type="file" id="rudra_upload_image" accept="image/jpeg,image/png" class="form-control"><span class="help-block">Select a JPG or PNG image. Uploaded images do not require cropping.</span></div></div></div></div>
<div id="rudra_camera_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4>Get Frame and Snap Image</h4></div><div class="modal-body"><label>Select Camera</label><select id="rudra_camera_select" class="form-control"><option>Detecting cameras...</option></select><br><video id="rudra_video" autoplay playsinline style="width:100%;background:#111"></video></div><div class="modal-footer"><button class="btn btn-primary" type="button" id="rudra_capture">Crop Image</button></div></div></div></div>
<div id="rudra_crop_modal" class="modal modern-modal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4>Crop and Save Image</h4></div><div class="modal-body"><img id="rudra_crop_image" alt="Captured Rudraksha" style="display:block;max-width:100%;width:100%"></div><div class="modal-footer"><button class="btn btn-primary" type="button" id="rudra_crop_save">Crop Image</button></div></div></div></div>
<script src="../js/cropper.min.js"></script><script src="../js/rudraksha_form.js"></script>
<?php include "assets/footer.php"; ?>
